---
title: "Gradebook Status Report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
params:
  topic_table: NA
  student_table: NA
  homework_table: NA
  review_grades: NA
  summary_grades: NA
  homework_grades: NA
  completed_topics: NA
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course Info

#### Roster
```{r, echo=FALSE, message=FALSE, warning=FALSE}
params$student_table
```

#### Homework Table
```{r, echo=FALSE, message=FALSE, warning=FALSE}
params$homework_table
```

#### Review Table 
```{r, echo=FALSE, message=FALSE, warning=FALSE}
params$topic_table
```

## Grades

#### Homework Grades
```{r, echo=FALSE, message=FALSE, warning=FALSE}
params$homework_grades
```

#### Topic Completion Summary
```{r, echo=FALSE, message=FALSE, warning=FALSE}
params$summary_grades
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}
params$completed_topics
```

#### Review Grades
```{r, echo=FALSE, message=FALSE, warning=FALSE}
params$review_grades
```